### ISSUE TITLE
More flexibility when shouldAutomaticallyDetectRange = true

### ISSUE THREAD

**Issue by spinach** [philackm/ScrollableGraphView#21]
First of all, great library, I really like it :)

I'm wondering if we could add more flexiblity to shouldAutomaticallyDetectRange = true. Right now, it will resize the graph depending on what is the max-y value and min-y value. I m wondering if we can add some vertical margin in there?

Example: if max-y value is 115, and y-margin is 15, then highest value in graph would be 130 and not 115 like it is now. 

I know that I can just find out what is my max y value and then compute the new rangeMax and rangeMin, but I think it would be nice to have it in the library. I can also help with that if need be, it should not be hard by looking at the code :)

**Comment by philackm** [comment]
Yeah, this should definitely be easy enough to implement.

Pull requests are always welcome. :p

**Comment by philackm** [comment]
Due to the new API, shouldAutomaticallyDetectRange has been removed. (This is so the graph view no longer has to touch any data that it is not displaying. The graph view will only touch data that appears on the screen. This allows for better integration with things like `NSManagedObjectContext`)

The user of the component is now responsible for setting a correct range when not `shouldAdaptRange` is set to false.
