### ISSUE TITLE
Update datasource to reference the  label(forPlot plot: Plot, atIndex pointIndex: Int) -> String not label(atIndex pointIndex: Int) -> String

### ISSUE THREAD

**Issue by devraj** [philackm/ScrollableGraphView#90]
XCode complains that this function is required by the data source
`func label(atIndex pointIndex: Int) -> String`

which is called when it wants the label information 

the example references
`func label(forPlot plot: Plot, atIndex pointIndex: Int) -> String`

**Comment by philackm** [comment]
It seems I had forgotten to update APIv4.md. 

I realised it only makes sense to have a single label for each point on the _graph_, the labels are the same no matter how many _plots_ are on the graph. I ended up removing the `forPlot plot: Plot` parameter from the `ScrollableGraphViewDataSource` protocol. Now the graph will ask the data source for a label for each point index that comes into view, and since the point index is not related to any one plot, there is no need for the plot parameter. I've updated the reference to reflect this.
